### ISSUE TITLE
fakester.biz dead

### ISSUE THREAD

**Issue by johnmolino** [integer-net/Anonymizer#6]
it seems that this code is not going to work anymore.... FYI

**Comment by diglin** [comment]
@avstudnitz what do you think about this?

**Comment by avstudnitz** [comment]
I should probably just delete this repository. AFAIK it's not used any more.

**Comment by razbakov** [comment]
@avstudnitz please either delete this repo or write *BOLD* in readme that fakester.biz is dead and module won't work anymore

**Comment by schmengler** [comment]
It was about time to release the complete rewrite based on Faker.js: I merged 2.0.0-rc2 into master, replacing the dead version
